name: json-validator
version: 0.1.0.0
synopsis: Validates JSON
description: Validates JSON.
github: tracsis/json-validator
license: BSD3
license-file: LICENSE
author: David Turner
maintainer: Tracsis plc
copyright: 2017 Tracsis plc
category: Web
build-type: Simple
extra-source-files: README.md

language: Haskell2010

tested-with: GHC ==8.10.7 || ==9.4.8 || ==9.8.2 || ==9.10.1 || ==9.12.1

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10 && < 1

library:
  source-dirs: src
  dependencies:
    - array >= 0.5 && < 1
    - containers >= 0.6 && < 1
    - mtl >= 2.2 && < 3
    - text >= 1.2 && < 3
    - word8 >= 0.1 && < 1

executables:
  json-validator-exe:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - json-validator
      - aeson >= 1.5 && < 3
      - criterion >= 1.5 && < 2
      - parallel >= 3.2 && < 4
      - text >= 1.2 && < 3

  dump-state-machine:
    source-dirs: dump-state-machine
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - json-validator

  json-test:
    source-dirs: json-test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - json-validator
